### ISSUE TITLE
Accessibility copy? 

### ISSUE THREAD

**Issue by williln** [djangocon/djangocon.us#60]
Any objection to adding an "Accessibility" page to the DjangoCon web site, perhaps under the "About" heading? It could state the following: 

- Commitment to accessibility by the DC organizers 
- The kind of info on the Django Under The Hood page: http://www.djangounderthehood.com/accessibility/  

It's helpful to potential attendees who might have an accessibility concern to have this information on the website, instead of forcing them to ask for it. I am willing to come up with initial copy, but can someone put me in touch with the venue so I can ask them some questions?

**Comment by craigbruce** [comment]
This is a really great idea and something we need. @SHayslerSF is liaising with AT&T so is best placed to put you in touch.

**Comment by jefftriplett** [comment]
No objection at all and great idea. I gave you admin access to the website and most of our content is in the CMS > Pages app and the hierarchy is in the sitetree > tree > main app. Feel free to make changes or we will queue it up to work on.

**Comment by williln** [comment]
Thanks! I'll work on it this week, and hopefully be in touch with @SHayslerSF soon to get info on the venue.

**Comment by williln** [comment]
## Commitment to Accessibility 

### Conference Venue 

The conference venue, [AT&T Executive Education and Conference Center](http://www.meetattexas.com/), has XXX accommodations. 

- Do they have step-free access to all parts of the conference? 
- Do they have elevators for events that happen on other floors? 
- Do they have accessible restrooms, and are those easily found? 
- Is there a quiet room/lactation room available? 
- Will service animals be welcome by the conference center? 

You can reach the conference venue by a bus that stops directly in front of the building. The [CapMetro Trip Planner](https://www.capmetro.org/planner/) can help you find the right bus from your hotel to the venue. All buses in Austin can "kneel" for easier boarding and are equipped with lifts or low-floor ramps. They can also accommodate your service animal. They will also accommodate your request to board or exit along a route other than a bus stop. You can [apply for a reduced fair card](https://www.capmetro.org/RFID/) if you have a disability, are over 65, or are on Medicare. 

#### For attendees with visual or auditory impairments

- Will we be doing live captioning like Pycon did? 

All buses in Austin announce stops verbally in English and Spanish. Most buses have a visual display of upcoming stops. 
 
If you have any special requests, please get in touch and we will see what we can do. 

### Sprint venue 

We are still working on confirming accessibility at the sprint venue. 

Thanks to [Django Under the Hood](http://www.djangounderthehood.com/accessibility/) for inspiration for our accessibility statement.

**Comment by williln** [comment]
I looked on the conference center web site for the answers to my questions about the venue, but I didn't see anything relevant on their site.

**Comment by jefftriplett** [comment]
cc'ing @SHayslerSF who has access to our venue reps to confirm. 

> Will we be doing live captioning like Pycon did?

I didn't even know this was possible until PyCon so there was no plan for it. I'll drop Diane Clark an email to see what the process and expense was like. You never know unless we ask so we can find out.

Since the UT campus is nearby, do you think they have any services which could help with these and some of the mental well being like DjangoCon EU provides? That might be a good place for us to start for any services which aren't covered by the venue and the campus is nearby.

**Comment by williln** [comment]
Jeff,

That's a great idea, about getting UT to help out. I've emailed my boss
about who I would email about that, and I'll let you know what I find out.
That DjangoCon EU page is fantastic.

Lacey

**Comment by freakboy3742** [comment]
@evildmp is another person to talk to about close captions - he's organised the same thing for DjangoCon Europe, so he might be able to give some indicative costs.

The mental health service at DjangoCon Europe came from my prompting (it's an idea that came from Linux.Conf.Au). Since the conference is associated (geographically, anyway) with UT at Austin, I'd suggest approaching the University student counselling service (if they have one) and/or the Psychology department. In DjangoCon Europe, it's not going to cost the conference anything, because there's a quid pro quo - the university provide the counselling service and a 20 minute talk for the program; the conference then invites them to the sprint so they can get some Django experts to build some simple web service that would be useful to them professionally. Don't know if the same thing will work for UT, but it's worth a try.

**Comment by williln** [comment]
I've reached out to the EAP (Employee Assistance Program) at UT about a
partnership, so I'll let you all know. UT does all their programming in
house and is still on a mainframe (talk to me about Django with a mainframe
backend!!) so that sort of partnership might not be possible, but my email
was very "we'd love to talk to you about ways to give back," so I'll let
you all know what they say.

**Comment by jefftriplett** [comment]
I reached out to the scipy-organizers list after I noticed their poll to see if anyone requires childcare assistance. I'm hoping that since we are in the same venue that maybe we can get some leads and resources.

**Comment by williln** [comment]
FYI, what I have so far is live. https://2015.djangocon.us/accessibility/

**Comment by freakboy3742** [comment]
Typo: "Reduced fair" card for public transport. Bonus points for the double entendre :-)

**Comment by williln** [comment]
/crawls under bed and eats her English degree....

**Comment by williln** [comment]
FYI, I emailed David at the conference center today with the questions I have outlined above, and will update the accessibility copy once he responds. I will close this issue once that is done.

**Comment by williln** [comment]
Have updated the accessibility statement with the info I got from David at the venue. Am closing this issue.

**Comment by jefftriplett** [comment]
Good work!
