### ISSUE TITLE
It's unclear how to donate to the financial aid fund

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#97]
It's not clear how to donate via Financial Aid so we should make that more clear from the page: https://2015.djangocon.us/financial_aid/

1. Sponsors (via Peter)
2. Directly (via our registration page when it's up *this week*.)

**Comment by williln** [comment]
Propose adding this section to the bottom: 

##How to Donate

- [Become a Sponsor](https://2015.djangocon.us/become-sponsor/)! You or your company can sponsor at a specific level, or can sponsor a particular need, such as wifi, meals, or sprints. Contact [Peter Baumgartner](mailto:sponsors@djangocon.us) directly to find out how you can sponsor us. 
- Donate Directly! When you purchase your ticket, you can either purchase an extra ticket for an attendee who couldn't otherwise afford it, or you can add a dollar amount of your choosing. 

(possible formatting errors-- dad's internet is slow and the preview won't load.)

**Comment by jefftriplett** [comment]
Looks a ton better than what we have now :)

**Comment by williln** [comment]
Done! Done on my phone so please double check when you get a chance.

**Comment by jefftriplett** [comment]
Looks good, thank you!
